version: '3'

services:
  kafka:
    image: wurstmeister/kafka:0.10.1.0
    expose:
      - "9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  # dataflow-server:
  #   image: springcloud/spring-cloud-dataflow-server-local:1.5.0.M1
  #   container_name: dataflow-server
  #   ports:
  #     - "9393:9393"
  #   environment:
  #     - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka:9092
  #     - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:2181
  #     - spring_datasource_url=jdbc:mysql://mysql:3306/dataflow
  #     - spring_datasource_username=root
  #     - spring_datasource_password=rootpw
  #     - spring_datasource_driver-class-name=org.mariadb.jdbc.Driver
  #     - spring.cloud.dataflow.applicationProperties.stream.spring.redis.host=redis
  #     - spring_redis_host=redis
  #   depends_on:
  #     - kafka
  #     - mysql
  #     - redis
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpw
    expose:
      - 3306
  redis:
    image: redis:2.8
    expose:
      - "6379"
